name: Test Build

# NOTE: build logic is duplicated here and in publish.yml

# Run on the master branch commit push and PRs to master (note conditional below)
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:
  build_wheels:

    # Only run if the commit message contains '[ci build]'
    if: "contains(toJSON(github.event.commits.*.message), '[ci build]') || contains(toJSON(github.event.pull_request.title), '[ci build]')"

    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            cibw-arch: manylinux_x86_64
          - runs-on: ubuntu-latest
            cibw-arch: manylinux_i686
          - runs-on: macos-latest
            cibw-arch: macosx_x86_64
          - runs-on: macos-latest
            cibw-arch: macosx_arm64
          - runs-on: macos-latest
            cibw-arch: macosx_universal2
          - runs-on: windows-latest
            cibw-arch: win_amd64
          - runs-on: windows-latest
            cibw-arch: win32
            python-arch: x86

    name: Build wheels ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}

    env:
      CIBW_BUILD_VERBOSITY: 3
      CIBW_BEFORE_BUILD_LINUX : "yum remove -y cmake && python -m pip install cmake && yum install -y libX11-devel libXcursor-devel libXrandr-devel libXinerama-devel mesa-libGL-devel mesa-libGL libXi-devel freeglut-devel mesa-libEGL-devel"
      CIBW_SKIP: "cp36-* cp313-*" # skip python 13 for now, builds failing

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Package source distribution
        if: runner.os == 'Linux'
        run: |
          python -m pip install build
          python -m build --sdist

      - name: Run cibuildwheel
        uses: pypa/cibuildwheel@v2.21 
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2

      # Upload binaries to the github artifact store
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: |
            ./wheelhouse/*.whl 
            ./wheelhouse/*.tar.gz 